spring:
  application:
    name: sunday-cloud-system
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sunday?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
    username: root
    password: root
dubbo:
  registry:
    address: nacos://localhost:8848
    register-mode: instance
    # dubbo 和 spring cloud 使用同一组时报错：https://github.com/apache/dubbo/issues/12145
    group: DUBBO_GROUP
  application:
    qos-enable: false
  consumer:
    check: false
    timeout: 6000
server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

jwt:
  secret: cfTcyKTcBpN32uyrG6NKeAsqoXXxbKmR

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl