spring:
  application:
    name: sunday-cloud-system

dubbo:
  registry:
    address: nacos://localhost:8848
    register-mode: instance
  application:
    qos-enable: false
  consumer:
    check: false
    timeout: 6000

server:
  port: 9000