### 新增菜单
POST {{gateway}}/admin-api/system/menu/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "菜单管理1",
  "type": 1,
  "parentId": 0,
  "path": "/system/menu",
  "component": "system/menu/index",
  "meta": {
    "icon": "fluent:book-information-24-regular",
    "order": 10,
    "i18nKey": "route.about"
  }
}

### 修改菜单
PUT {{gateway}}/admin-api/system/menu/update
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 19,
  "name": "菜单管理12",
  "type": 1,
  "sort": 1,
  "parentId": 0,
  "path": "/system/menu",
  "component": "system/menu/index",
  "componentName": "Menu"
}

### 删除菜单
DELETE {{gateway}}/admin-api/system/menu/delete?id=19
Content-Type: application/json
Authorization: Bearer {{token}}

### 获取菜单分页列表
GET {{gateway}}/admin-api/system/menu/page
Content-Type: application/json
Authorization: Bearer {{token}}


### 获取菜单精简信息列表
GET {{gateway}}/admin-api/system/menu/list-simple-tree
Content-Type: application/json
Authorization: Bearer {{token}}
