name: docker-sunday-cloud
services:
  nacos:
    image: nacos/nacos-server:v2.3.2-slim
    hostname: nacos-server
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=security
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
    ports:
      - "8848:8848"
      - "9848:9848" # gRPC port
    volumes:
      - nacos_data:/home/nacos/data

  mysql:
    image: mysql:8.2.0
    hostname: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7.2.4
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server

volumes:
  nacos_data:
    driver: local
  mysql_data:
    driver: local
  redis_data:
    driver: local