server:
  port: 80

spring:
  application:
    name: sunday-cloud-gateway
  config:
    import:
      - optional:classpath:application-${spring.profiles.active}.yaml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://sunday-cloud-system
          predicates:
            - Path=/auth/**
        - id: system-admin
          uri: lb://sunday-cloud-system
          predicates:
            - Path=/admin-api/system/**
        - id: system-app
          uri: lb://sunday-cloud-system
          predicates:
            - Path=/app-api/system/**

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never